# EBPR-Mapping CHTC Submission Script

# HTCondor Universe
universe = vanilla
log = EBPRmapping_$(Cluster).log
error = EBPRmapping_$(Cluster)_$(Process).err
requirements = (OpSys == "LINUX") && (Target.HasGluster == true) && (OpSysMajorVer =?= 7)

# Exectuables
executable = executables/EBPR-Mapping.sh
arguments = $(ref) $(meta) $(outname)
output = EBPRmapping_$(Cluster).out

# Transferring Files
# should_transfer_files = YES
# when_to_transfer_output = ON_EXIT
transfer_input_files = /home/emcdaniel/software/BBMap_38.07.tar.gz,/home/emcdaniel/software/samtools.tar.gz

# Compute resources 
request_cpus = 4
request_memory = 5GB
request_disk = 50GB


queue ref,meta,outname from /home/emcdaniel/mappingCombos.txt



