################
# mapMetasToRefs.sub
# Submission script for mapping metagenomic reads to a ref genome or assembly
# Elizabeth McDaniel


request_cpus = 4
request_memory = 10GB

executable = /home/GLBRCORG/emcdaniel/EBPR/coassembly/executables/mapMetasToRefs.sh
arguments = $(ref) $(meta) $(out)

output = /home/GLBRCORG/emcdaniel/EBPR/coassembly/outs/$(Cluster)_$(Process)_mapping.out
error = /home/GLBRCORG/emcdaniel/EBPR/coassembly/errs/$(Cluster)_$(Process)_mapping.err
log = /home/GLBRCORG/emcdaniel/EBPR/coassembly/logs/$(Cluster)_$(Process)_mapping.log

queue ref,meta,out from /home/GLBRCORG/emcdaniel/EBPR/coassembly/metadata/ebpr-indv-assemb-mappings.txt
