##################
# metabat_binning.sub
# Submission script for binning on GLBRC with MetaBat
# Elizabeth McDaniel
##################

request_cpus = 4
request_memory = 5GB

executable = /home/GLBRCORG/emcdaniel/EBPR/coassembly/executables/binning-metabat.sh
arguments = $(ASSEMB)

output = /home/GLBRCORG/emcdaniel/EBPR/coassembly/outs/$(Cluster)_$(Process)_binning.out
error = /home/GLBRCORG/emcdaniel/EBPR/coassembly/errs/$(Cluster)_$(Process)_binning.err
log = /home/GLBRCORG/emcdaniel/EBPR/coassembly/logs/$(Cluster)_$(Process)_binning.log

queue ASSEMB from /home/GLBRCORG/emcdaniel/EBPR/coassembly/metadata/ebpr-assemblies.txt
