################
# parse-mapping-stats.sub
# Parse mapping stats from depth files
# Elizabeth McDaniel


request_cpus = 4
request_memory = 10GB

executable = /home/GLBRCORG/emcdaniel/EBPR/coassembly/executables/parse-depth-files.sh
arguments = $(ref) $(meta) $(depth)

output = /home/GLBRCORG/emcdaniel/EBPR/coassembly/outs/$(Cluster)_$(Process)_calc_stats.out
error = /home/GLBRCORG/emcdaniel/EBPR/coassembly/errs/$(Cluster)_$(Process)_calc_stats.err
log = /home/GLBRCORG/emcdaniel/EBPR/coassembly/logs/$(Cluster)_$(Process)_calc_stats.log

queue ref,meta,depth from /home/GLBRCORG/emcdaniel/EBPR/coassembly/metadata/queue-parsing-depth-files.txt