# Python Interactive Installation Submission 
# Referencing http://chtc.cs.wisc.edu/inter-submit.shtml

# logfile
log = pyinteractive.log

# STD out
output = process.out
error = process.err

+IsBuildJob = true
requirements = (OpSysMajorVer =?= 7) && ( IsBuildSlot == true )

# Transfer for interactive installation 
transfer_input_files = software/Python-2.7.15.tgz

# compute resources 
request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue 

