# chtc-checkm-all.sub
#
#
# Specify the HTCondor Universe
universe = vanilla

log = prodigal_$(Cluster).log
error = prodigal_$(Cluster)_$(Process).err
requirements = (OpSysMajorVer == 7)
#
# Specify your executable, arguments, and a file for HTCondor to store standard
#  output.
executable = executables/run-prodigal.sh
arguments = $(binarchive)
output = prodigal_$(Cluster).out
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(binarchive),software/prodigal.tar.gz
#transfer_output_files = 
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.

request_cpus = 2
request_memory = 10GB
request_disk = 5GB
#
# Tell HTCondor to run every fastq file in the provided list:
queue binarchive from EBPR-Bins-NUCS/EBPR-NUCS-list.txt