# SOAPdenovo Interactive Session Installation
# Referencing http://chtc.cs.wisc.edu/inter-submit.shtml

# logfile
log = interactive.log

# STD out
output = process.out
error = process.err

+IsBuildJob = true
requirements = (OpSysMajorVer =?= 7) && ( IsBuildSlot == true )

# Transfer for interactive installation 
transfer_input_files = SOAPdenovo2-bin-LINUX-generic-r240.tgz,GapCloser-src-v1.12-r6.tgz

# compute resources 
request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue 

