# split fastq transcriptome files 

# HTCondor Universe
universe = vanilla
log = splitfastq_$(Cluster).log
error = splitfastq_$(Cluster)_$(Process).err
requirements = (OpSys == "LINUX") && (Target.HasGluster == true) && (OpSysMajorVer =?= 7)

# Exectuables
executable = executables/splitfastq.sh
arguments = $(transcriptome)
output = splitfastq_$(Cluster).out

# Transferring Files
# should_transfer_files = YES
# when_to_transfer_output = ON_EXIT
transfer_input_files = /home/emcdaniel/software/BBMap_38.07.tar.gz

# Compute resources 
request_cpus = 4
request_memory = 50GB
request_disk = 100GB

queue transcriptome from /home/emcdaniel/transcriptomeList.txt